# Generated by Django 6.0 on 2026-01-08 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shopscan_app.product')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_sales', to='shopscan_app.shop')),
                ('shopkeeper', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_sales', to='shopscan_app.shopkeeper')),
            ],
        ),
    ]
