# Generated by Django 6.0 on 2026-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0002_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_scan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
