# Generated by Django 6.0 on 2026-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0004_payment_plan_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
