# Generated by Django 6.0 on 2026-01-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0005_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
