# Generated by Django 6.0 on 2026-01-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0006_alter_shopkeeper_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/profiles/profile_HIgBKoo.jpg', null=True, upload_to='profiles/'),
        ),
    ]
