# Generated by Django 6.0 on 2026-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopscan_app', '0007_alter_shopkeeper_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_generate_barcode',
            field=models.BooleanField(default=False),
        ),
    ]
